# Generated by Django 2.2.4 on 2021-04-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='destination',
            new_name='group_name',
        ),
    ]
