# Generated by Django 2.2.4 on 2021-04-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_id',
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='messages_group', to='app.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='app.User'),
        ),
    ]
